name: Action workflow

on:
  push:
  #  branches-ingore: # stabilisce su quali rami far girare le richieste
    branches: #stabilice su quali rami attivare le azioni
    - master 
    - 'feature/*' # l'asterisco è come il like di sql
    tags:
    - v1.*
    paths:
      - "**.js"
  # repository_dispatch:
  # types: [build]
  #schedule:
  # - cron: "0/5 * * * * " 
  # - cron: "0/6 * * * * "
  #push:
  #pull_request:
  #  types: [closed, assigned, opened, reopened]


jobs:
 run-github-actions:
  runs-on: ubuntu-latest
  steps:
    - name: List file
     # quelle col dollaro sono tutte variabili di ambiente utili pre settate che si rifanno a delle specifice sdi git hib
      run: |
        pwd
        ls
        echo $GITHUB_SHA
        echo $GITHUB_REPOSITORY
        echo $GITHUB_WORKSPACE   
        echo "${{github.token}}"
      #   git clone git@hub:$GITHUB_REPOSITORY
      #   git checkout $GITHUB_SHA
    - name: Checkout
      uses: actions/checkout@v1
    - name: List file after
      run: |
        pwd
        ls -a
    - name: Simple JS Action
      id: greet
      uses: actions/hello-world-javascript-action@v1 # questa è un action importtata da esterno , queste informazioni le prendiamo dal url prima della chiocciola
                                                    # la chiocciola è la versione
      with:     # è una parola chiave per gli input che andranno nel azione
       who-to-greet:  John 
    - name: Log Greeting Time  
      run: echo "${{steps.greet.outputs.time}}" #questa è una variabile che contiene l' output dello steap soapra. output specifica che ci si riferisce a un
                                                # output mentre time  è relativo al azione specifica
