name: container 
on: push 

jobs: 
  doker-steaps:
   runs-on: ubuntu-latest
   container: 
    image: node:10.18.0-jessie
   steps:
    - name: log node version
      run: node -v
       
    - name: save paht for node
      run: |
       echo  " PHAT_NODE= $(type -a node) " >>  $GITHUB_ENV 
    - name: Steap whit doker 
      uses: docker://node:12.14.1-alpine3.10
      with:
       entrypoint: $PHAT_NODE     ##'/bin/echo'
       args: 'Hello Word'        
  node-doker:
   runs-on: ubuntu-latest
   services:
    app:
     image: alialaa17/node-api
     ports:
      - 3001:3000
    mongo:
     image: mongo
     ports:
      - "27017:27017"
   steps:
   - name: Post a  user
     run: "curl -X POST http://localhost:3001/api/user -H 'Content-Type: application/json' -d  '{\"username\": \"hello\", \"address\": \"dwdw\" }'"
   - name: GET s users
     run: "curl -X GET http://localhost:3001/api/users "  

   

     
   
