name: first  # il nome di tutto il workflow

on: [push ] #definisce gli eventi entro cui si applicano le configurazioni

jobs:
 run-shell-comand:  #il nome del job
  runs-on: ubuntu-latest  # il sistema oeprativo dove gira
  steps: 
   - name: echo a string
     run:  echo "Hello Word"
   - name: multi line screapt
     run: | # il pipe è utilizzato per poter lanciare più comandi contemporaneamente
       docker -v 
   - name: python Commands
     run:  |
      import platform 
      print(platform.processor())
     shell: python # specifca la shell con cui viene lanciato il  comando di deafolt è bash  

     
   