name: Matrix

on: push

jobs:
  node-version:
    runs-on: ${{matrix.os}}
    env:
     IS_UBUNTU_8: ${{matrix.is_ubuntu_8}}
    strategy:
     matrix:
       os: [macos-latest, ubuntu-latest, windows-latest ]
       node_version: [6,8,10]
       include:
        - os: ubuntu-latest
          node_version: 4 
          is_ubuntu_8: "true"
       exclude:
        - os: ubuntu-latest
          node_version: 6
     max-parallel: 3    # stabilisce il numero massimo di job che possono andare in parallelo
     fail-fast: true
    steps:
    - name: Log node version 
      run: node -v 
    - uses: actions/setup-node@v2
      with:
       node-version: ${{matrix.node_version}}
    - name: Log node version again 
      run: |
       node -v
       echo $IS_UBUNTU_8
        
  